name: Build and Deploy Book
on:
  push:
    branches:
    - main
  schedule:
  - cron: 0 15 * * *
jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install dependencies
      run: python -m pip install --upgrade pip; pip install -r book/requirements.txt
    - name: Setup Git
      run: git config --global init.defaultBranch main;git config --global user.email
        "leo@dumbartonserum.com";git config --global user.name "Leo Dumbarton";git
        pull --tags
    - name: Build the book
      run: datazimmer load-explorer-data && jupyter-book build book
      env:
        ZIMMER_FULL_AUTH: ${{ secrets.ZIMMER_FULL_AUTH }}
        GIT_HTTPS_TOKEN: ${{ secrets.GIT_HTTPS_TOKEN }}
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: book/_build/html
